<?php

namespace Container4MXB4N2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RJ7865fService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.rJ7865f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rJ7865f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'exercise' => ['privates', '.errored..service_locator.rJ7865f.App\\Entity\\ExerciseStorage', NULL, 'Cannot autowire service ".service_locator.rJ7865f": it needs an instance of "App\\Entity\\ExerciseStorage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'exercise' => 'App\\Entity\\ExerciseStorage',
        ]);
    }
}
