<?php

namespace Container4MXB4N2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExerciseStorageService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.rJ7865f.App\Entity\ExerciseStorage' shared service.
     *
     * @return \App\Entity\ExerciseStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rJ7865f": it needs an instance of "App\\Entity\\ExerciseStorage" but this type has been excluded in "config/services.yaml".');
    }
}
