<?php

namespace Container4MXB4N2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromoCodesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PromoCodesRepository' shared autowired service.
     *
     * @return \App\Repository\PromoCodesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PromoCodesRepository'] = new \App\Repository\PromoCodesRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
