<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4MXB4N2\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4MXB4N2/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container4MXB4N2.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container4MXB4N2\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container4MXB4N2\App_KernelProdContainer([
    'container.build_hash' => '4MXB4N2',
    'container.build_id' => '936f2bdc',
    'container.build_time' => 1693213036,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4MXB4N2');
