<?php

namespace Container0vmPPKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiveClassControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\LiveClassController' shared autowired service.
     *
     * @return \App\Controller\LiveClassController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\LiveClassController'] = $instance = new \App\Controller\LiveClassController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\LiveClassController', $container));

        return $instance;
    }
}
