<?php

namespace Container0vmPPKJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoStorageRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\VideoStorageRepository' shared autowired service.
     *
     * @return \App\Repository\VideoStorageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\VideoStorageRepository'] = new \App\Repository\VideoStorageRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
