<?php

namespace ContainerXNq9CcK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Db54xSnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.db54xSn' shared service.
     *
     * @return \App\Controller\Session
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\LiveClassController::liveStream()": the $session argument is type-hinted with the non-existent class or interface: "App\\Controller\\Session". Did you forget to add a use statement?');
    }
}
