<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxaD4Zl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxaD4Zl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQxaD4Zl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQxaD4Zl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQxaD4Zl\App_KernelDevDebugContainer([
    'container.build_hash' => 'QxaD4Zl',
    'container.build_id' => 'e2bf28fc',
    'container.build_time' => 1693157464,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxaD4Zl');
